server:
  port: 88

spring:
  application:
    name: shoppingmall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: login
          uri: lb://renren-fast
          predicates:
            - Path=/api/sys/**,/api/captcha.jpg**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
        # 匹配原理,uri是重定向后的地址，根据nacos注册中心的服务名找到ip和端口
        # 当predicates断言成立时，就会将发往网关的请求重定向至配置的uri地址，其中如果filters有配置，则会根据filters的配置修改请求信息
        - id: product_category
          uri: lb://shoppingmall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://shoppingmall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: coupon_route
          uri: lb://shoppingmall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://shoppingmall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party
          uri: lb://shoppingmall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: search_route
          uri: lb://shoppingmall-search
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api/search/(?<segment>.*),/$\{segment}

#        注意该项配置需要放在最后，因为网关的配置是按照路由配置顺序来逐个扫描，找到符合规则的就会直接转发，不会再向下寻找
        - id: fromNginx_route
          uri: lb://shoppingmall-product
          predicates:
            - Host=192.168.56.10
