server:
  port: 17000
  servlet:
    session:
      timeout: 10m

spring:
  application:
    name: shoppingmall-cart
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.56.10:3306/shoppingmall_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  jackson:
    date-format: yyyy-MM-dd hh:mm:ss
    time-zone: GMT+8
  redis:
    host: 192.168.56.10
    port: 6379
  session:
    store-type: redis
    redis:
      namespace: spring:session
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.56.10
    port: 5672
    username: guest
    password: guest
    #确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    #确认消息已发送到队列(Queue)
    publisher-returns: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

# 配置sql日志输出
logging:
  level:
    com.anzaiyun.shoppingmall: debug