server:
  port: 30000

spring:
  application:
    name: shoppingmall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
      access-key: LTAI4Fzqdnk1guSMpuokSQZ5
      secret-key: tDNe03mZBo8GjIA4ZDSHiGFoHntsay
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com

management:
  endpoints:
    web:
      exposure:
        include: '*'