server:
  port: 30000

spring:
  application:
    name: shoppingmall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alicloud:
#      已经废弃不做使用，这里仅做演示
      access-key: LTAI4Fzqdnk1guSMpuokSQZ5
      secret-key: tDNe03mZBo8GjIA4ZDSHiGFoHntsay
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
      sms:
        host: "https://gyytz.market.alicloudapi.com"
        path: "/sms/smsSend"

management:
  endpoints:
    web:
      exposure:
        include: '*'